[package]
name = "amygui"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
raylib = { version = "5.5.1", features = ["custom_frame_control", "nogif"] }

[build-dependencies]
cc = "1.0"
